# https://aka.ms/yaml

variables:
  LIBRARY_PATH: /lib:/usr/lib

jobs:
- job: test
  displayName: 'Lint & Test'

  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    PIP_CACHE_DIR: ".cache/pip"
    PIP_SRC: ".cache/src"

  - task: UsePythonVersion@0
    displayName: 'Set Python version'
    inputs:
      versionSpec: '3.7.x'
      addToPath: true

  - script: pip3 install poetry
    displayName: 'Install Poetry'

  - script: |
      poetry config settings.virtualenvs.create false
      poetry install
    displayName: 'Install project using Poetry'

  - script: python3 -m flake8
    displayName: 'Run linter'

- job: build
  displayName: 'Build Containers'
  dependsOn: 'test'

  steps:
  - task: Docker@1
    displayName: 'Login: Docker Hub'

    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'DockerHub'
      command: 'login'

  - script: docker --version
    displayName: 'Check Docker version'

  - task: ShellScript@2
    displayName: 'Build and deploy containers'

    inputs:
      scriptPath: scripts/deploy-azure.sh
