[tool.poetry]
name = "bot"
version = "0.1.0"
description = "A Discord bot that changes with the seasons."
authors = ["The Python Discord community"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
arrow = "^0.13.1"
beautifulsoup4 = "^4.7"
aiodns = "^1.2"
pillow = "^5.4"
pytz = "^2018.9"
"discord.py" = {git = "https://github.com/Rapptz/discord.py", branch = "3f06f24"}
fuzzywuzzy = "^0.17.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
flake8-bugbear = "^18.8"
flake8-import-order = "^0.18.0"
flake8-tidy-imports = "^2.0"
flake8-todo = "^0.7.0"
flake8-string-format = "^0.2.3"
pre-commit = "^1.14"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
